ConvertFrom-StringData @'
    Encryptor = ENCRYPTOR
    DotNetConfiguration = DotNet Configuration
    DotNetConfigurationHelp = Use this option to change the .NET configuration
    DotNetConfigurationMenu = .NET CONFIGURATION MENU
    CurrentConfiguration = View Current Configuration
    CurrentConfigurationHelp = Use this option to view the current .NET configuration
    CurrentConfigurationTitle = CURRENT CONFIGURATION
    UpdateConfiguration = Update Configuration
    UpdateConfigurationHelp = Use this option to update the .NET configuration
    KeyContainerManagement = Key Container Management
    KeyContainerManagementHelp = Use this option to manage key containers
    KeyContainerManagementMenu = KEY MANAGEMENT MENU
    NewKeyContainer = New Key Container
    NewKeyContainerHelp = Use this option to create a new key container
    NewKeyContainerTitle = NEW KEY CONTAINER
    RemoveKeyContainer = Remove Key Container
    RemoveKeyContainerHelp = Use this option to remove an existing key container
    RemoveKeyContainerTitle = REMOVE KEY CONTAINER
    ImportKeyContainer = Import Key Container
    ImportKeyContainerHelp = Use this option to import a key container
    ImportKeyContainerTitle = IMPORT KEY CONTAINER
    ExportKeyContainer = Export Key Container
    ExportKeyContainerHelp = Use this option to export a key container
    ExportKeyContainerTitle = EXPORT KEY CONTAINER
    GrantAccessKeyContainer = Grant Access to Key Container
    GrantAccessKeyContainerHelp = Use this option to grant access to a specific key container
    GrantAccessKeyContainerTitle = GRANT ACCESS TO KEY CONTAINER
    ConfigurationFileSecurity = Configuration File Security
    ConfigurationFileSecurityHelp = Use this option to encrypt/decrypt configuration files
    ConfigurationFileSecurityMenu = CONFIGURATION FILE SECURITY MENU
    EncryptIISConfiguration = Encrypt IIS Configuration
    EncryptIISConfigurationHelp = Use this option to encrypt a configuration file in an IIS website
    EncryptLocalConfiguration = Encrypt Local Configuration
    EncryptLocalConfigurationHelp = Use this option to encrypt a configuration file in the local system
    DecryptIISConfiguration = Decrypt IIS Configuration
    DecryptIISConfigurationHelp = Use this option to decrypt a configuration file in an IIS website
    DecryptLocalConfiguration = Decrypt Local Configuration
    DecryptLocalConfigurationHelp = Use this option to decrypt a configuration file in the local system
    ProtectConfigurationTitle = {0} CONFIGURATION
    AvailableWebsites = Available Websites
    SelectWebSite = Select the website to use
    SelectedWebSite = Selected Website is '|{0}|'
    AvailableWebApplications = Available Web Applications in '|{0}|'
    SelectWebApplication = Select the web application to use
    SelectedWebApplication = Selected Web Application is '|{0}|'
    AvailableSecurityProviders = Available Security Providers in '|{0}/{1}|' config file
    LocalAvailableSecurityProviders = Available Security Providers in '|{0}|' config file
    SelectSecurityProvider = Select the security provider to use
    SelectedSecurityProvider = Selected Security Provider is '|{0}|'
    ConfigurationSection = Configuration Section in '|{0}/{1}|' config file
    ConfigurationSectionWithDefault = Configuration Section to {0} [Default is '{1}']
    LocalConfigurationSection = Configuration Section in '|{0}|' config file
    SelectedConfigurationSection = Selected Configuration Section is '|{0}|'
    LocationConfigurationFile = Location of config file
    LocalPathConfigurationFile = Local path (directory) to config file to {0}
    SelectedLocalPathConfigurationFile = Selected local path to config file is '|{0}|'
    Account = Account (DOMAIN\\ACCOUNT)
    RuntimePath = Runtime path
    NewRuntimePath = New Runtime Path
    AvailableRuntimes = Available Runtimes
    SelectRuntime = Select the runtime to use
    SearchingForRuntimes = Searching for runtimes, please wait...
    RuntimeChangedConfiguration = Runtime changed from |{0}| to |{1}|
    KeyContainerName = Key container name
    KeyContainerXmlFile = Key container xml file
    FileDropLocation = File drop location
    Exit = Exit
    ExitHelp = Use this option to quit the application
    ExitAndClose = Exist and Close
    ExitAndCloseHelp = Use this option to quit the application and close the powershell session
    GoBack = Go Back
    GoBackHelp = Use this menu to go back to the previous screen
    Help = Help
    Cancel = Cancel
    Preselected = Preselected
    InvalidOption = {0} is not a valid option, please select an option from the list
    NextAction = What would you like to do?
    EnterToContinue = Press enter to continue
    VerboseOpeningDotNetConfiguration = Opening .NET Configuration
    VerboseOpeningKeyManagement = Opening Key Management
    VerboseOpeningConfigurationFileSecurity = Opening Configuration File Security
    VerboseExitingEncryptor = Exiting Encryptor
    VerboseDisplayingRuntimeInformation = Displaying runtime information
    VerboseOpeningUpdateRuntimePathWizard = Opening Update Runtime Path wizard
    VerboseBackToEncryptorMenu = Back to Encryptor menu
    VerboseOpeningNewKeyContainerWizard = Opening New Key Container wizard
    VerboseOpeningRemoveKeyContainerWizard = Opening Remove Key Container wizard
    VerboseOpeningImportKeyContainerWizard = Opening Import Key Container wizard
    VerboseOpeningExportKeyContainerWizard = Opening Export Key Container wizard
    VerboseOpeningGrantAccessKeyContainerWizard = Opening Grant Access Key Container wizard
    VerboseCalling = Calling {0}
    VerboseOpeningEncryptIISConfigurationFileWizard = Opening Encrypt IIS Configuration File Wizard
    VerboseOpeningEncryptLocalConfigurationFileWizard = Opening Encrypt Local Configuration File Wizard
    VerboseOpeningDecryptIISConfigurationFileWizard = Opening Decrypt IIS Configuration File Wizard
    VerboseOpeningDecryptLocalConfigurationFileWizard = Opening Decrypt Local Configuration File Wizard
'@